name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Smoke check
        run: python scripts/smoke_check.py

      - name: Run tests
        run: pytest -q

      - name: Token estimation spot check
        run: python - <<'PY'
from src.metrics import estimate_tokens
print('Tokens:', estimate_tokens('Churn prevention via onboarding improvements.'))
PY
